spring.h2.console.enabled=true
server.port=8085

spring.datasource.url=jdbc:mysql://localhost:3306/ebank?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# =========================
# ACTUATOR + PROMETHEUS
# =========================

management.endpoints.web.exposure.include=*
management.endpoint.prometheus.access=unrestricted
management.prometheus.metrics.export.enabled=true

# =========================
# Kibana
# =========================

logging.file.name=C:/Users/Dell/Downloads/PFE/monitoring/logs/application.log
logging.level.root=INFO